### ISSUE TITLE
Getting Error Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wp_set_excerpt_length' not found or invalid function name in C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php on line 298

### ISSUE THREAD

**Issue by anurag-kalita** [mattbanks/WordPress-Starter-Theme#24]
Hi, 
I'm getting this error when I try to add this function for the _excerpt length_.

```
function wp_set_excerpt_lenght( $length ){
	return 20;
}

add_filter( 'excerpt_length', 'wp_set_excerpt_length');
```
**Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'wp_set_excerpt_length' not found or invalid function name in C:\xampp\htdocs\wordpress\wp-includes\class-wp-hook.php on line 298**

![dw](https://user-images.githubusercontent.com/24487915/29494299-b78d7738-85c4-11e7-818b-3091be30360c.jpg)

![browser](https://user-images.githubusercontent.com/24487915/29494304-c5d8ef52-85c4-11e7-9faf-d37f39a8c60e.jpg)

I'm new to Wordpress actually.

Can you help in here?
Thanks in advance.

**Comment by mattbanks** [comment]
Looks like you have a typo in `function wp_set_excerpt_lenght( $length )`. Should be `function wp_set_excerpt_length( $length )` to match the name of the function you passed in the filter. 😄
