### ISSUE TITLE
 Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'ReduxFramework' does not have a method '_options_page' in /home4/wilmer/public_html/wp-includes/plugin.php on line 525

### ISSUE THREAD

**Issue by Miguel99990** [mattbanks/WordPress-Starter-Theme#26]
Me aparece este error:

Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'ReduxFramework' does not have a method '_options_page' in /home4/wilmer/public_html/wp-includes/plugin.php on line 525

Me puede ayudar a solucionarlo.

**Comment by mattbanks** [comment]
Hey @Miguel99990!

That error looks like it's coming from Redux Framework based on the error message stating it's coming from that class. You can get in touch with them to ask for support - https://wordpress.org/plugins/redux-framework/ :)

**Comment by Miguel99990** [comment]
Gracias...
